#!/bin/sh

#Download Chrome
wget --no-check-certificate "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" -P /tmp/;

#Install Chrome
sudo dpkg -i /tmp/google-chrome-stable_*.deb;

#Cleanup Chrome
rm /tmp/google-chrome-stable_*.deb;
