#!/bin/bash

#Set docker4wordpress package alias to download the file for project
sudo printf "#!/bin/bash\n wget https://github.com/wodby/docker4wordpress/blob/master/docker-compose.yml" >> /tmp/docker4wordpress &&
sudo mv /tmp/docker4wordpress /usr/local/bin/ &&
sudo chmod +x /usr/local/bin/docker4wordpress;
