#!/bin/bash

#Install drush.
sudo composer global require drush/drush
export PATH="$HOME/.config/composer/vendor/bin:$PATH"

#Install drush launcher.
wget -O drush.phar https://github.com/drush-ops/drush-launcher/releases/download/0.4.2/drush.phar &&
chmod +x drush.phar &&
sudo mv drush.phar /usr/local/bin/drush;
drush --version;
