#!/bin/bash

#Install Node 8.
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - &&
sudo apt-get install -y nodejs;

#Install build-tools
sudo apt-get install -y build-essential;
node -v;
npm -v;
