#!/bin/bash

#Download PHPBrew.
wget --no-check-certificate https://github.com/phpbrew/phpbrew/raw/master/phpbrew -P /tmp/ &&
chmod +x /tmp/phpbrew &&

#Install PHPBrew.
sudo mv /tmp/phpbrew /usr/local/bin/phpbrew;
phpbrew -v;
phpbrew init;
