#!/bin/bash

#Install Attlasian Stride
 sudo sh -c 'echo "deb https://packages.atlassian.com/debian/stride-apt-client $(lsb_release -c -s) main" > /etc/apt/sources.list.d/atlassian-stride.list' &&
wget -O - https://packages.atlassian.com/api/gpg/key/public | sudo apt-key add - &&
sudo apt-get update &&
sudo apt-get install stride -y; 

